export const GET_REFERRAL_ID_ERROR = "GET_REFERRAL_ID_ERROR";
export const GET_REFERRAL_ID_SUCCESS = "GET_REFERRAL_ID_SUCCESS";
export const LOAD_PROFILE_PENDING = "LOAD_PROFILE_PENDING";
export const LOAD_PROFILE_ERROR = "LOAD_PROFILE_ERROR";
export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS";
